caddy-ingress-controller:
  # Replicas
  replicaCount: 1

  # Ingress controller configuration
  ingressController:
    config:
      email: "your-email@example.com"
      debug: false
      metrics: true

  # LoadBalancer service
  loadBalancer:
    enabled: true

  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
