apiVersion: v2
name: nginx-ingress
description: NGINX Ingress Controller with cert-manager integration
type: application
version: 1.0.0
appVersion: "1.11.3"

dependencies:
  - name: ingress-nginx
    version: "4.11.3"
    repository: https://kubernetes.github.io/ingress-nginx
