apiVersion: v2
name: traefik
description: Traefik ingress controller for K3s
type: application
version: 1.0.0
appVersion: "3.3.6"

dependencies:
  - name: traefik
    version: "37.2.0"
    repository: https://traefik.github.io/charts
