# Custom values for Traefik
# These override the defaults from the official Traefik chart

traefik:
  # Deployment configuration
  deployment:
    replicas: 1

  # Ports configuration
  ports:
    web:
      port: 8000
      exposedPort: 80
    websecure:
      port: 8443
      exposedPort: 443
      tls:
        enabled: true
    metrics:
      port: 9100

  # Service configuration
  service:
    enabled: true
    type: LoadBalancer

  # Dashboard configuration
  dashboard:
    enabled: true

  # Providers
  providers:
    kubernetesCRD:
      enabled: true
      allowEmptyServices: true
    kubernetesIngress:
      enabled: true
      allowEmptyServices: true
      publishedService:
        enabled: true

  # Metrics
  metrics:
    prometheus:
      enabled: true
      entryPoint: metrics

  # Logs
  logs:
    general:
      level: INFO

  # Security context
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  # Tolerations for control plane nodes
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

  # Priority class for system critical workloads
  priorityClassName: "system-cluster-critical"
