apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tim@schenanigans.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - schenanigans.com
          - home.schenanigans.com
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tim@schenanigans.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - schenanigans.com
          - home.schenanigans.com
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: token
